include theme.conf

font_family      Source Code Pro
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13

enable_audio_bell no
background_opacity 0.825
resize_in_steps no

tab_bar_min_tabs            2
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

window_margin_width 0
