# LIMBO

active_tab_foreground   #000000
active_tab_background   #6C81C0
active_tab_font_style   bold-italic
inactive_tab_foreground #bdbdbd
inactive_tab_background #222222
inactive_tab_font_style bold-italic

background            #000000
foreground            #bdbdbd
selection_background  #333333
selection_foreground  #ffffff
cursor                #9e9e9e
cursor_text_color     #080808
url_color             #80a0ff

# Normal colors
color0  #000000
color1  #ff5d5d
color2  #5D9666
color3  #AEAE68
color4  #6C81C0
color5  #cf87e8
color6  #6CA4C3
color7  #eeeeee

# Bright colors
color8   #333333
color9   #ff5189
color10  #57795D
color11  #8F8F5E
color12  #656E8A
color13  #ae81ff
color14  #6D8FA1
color15  #bbbbbb


